### ISSUE TITLE
Support for "unmark" flow annotation

### ISSUE THREAD

**Issue by vsimko** [d3sreq/foam-tool#13]
In order to support "mode switching", we probably need a new flow annotations `#unmark` which is an opposite of `#mark`, i.e., it switches the given goolean variable to `false`.

Usage:
   #mark:modeA
   #unmark:modeB
   ...
   #mark:modeB
   #unmark:modeA

**Comment by jiri-vinarek** [comment]
implemented in commit e453a8b7529fe7c4d3b0138742c289f030425dfc .

Unmark annotation simply sets boolean variable to ```false```, ```mark``` annotation doesn't have to precede ```unmark``` (this situation is not treated as error).

In model ```Mark``` class now has boolean flag ```value```, setting this flag to ```false``` is treated as ```unmark```.
